### ISSUE TITLE
Replit code does not run

### ISSUE THREAD

**Issue by hippyaki** [codewithpom/ISRO-API#2]
Without deploying the server, How did you test it? The ISRO original API works fine with GET method.

I went through the code, and it has something to do with the responses of Twitter followers as well.  

npm won't start as the consumer key of Twitter is not provided. For additional features for personal projects, you can make a private repo to use with your private keys. 

I have made changes in PR #1 for the code to work without any conflict.

**Comment by codewithpom** [comment]
Yes sorry as I have told you I am in my village so I am returning tomorrow
and tomorrow I will accept the PR.

With Regards and Thanks
Padmashree

**Comment by codewithpom** [comment]
Cool and thanks
